# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-22 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('Potrait', 'Potrait'), ('LandScape', 'Landscape'), ('Animals', 'Animals'), ('Street', 'Street'), ('Design', 'Design')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
