# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-22 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='category',
            field=models.CharField(choices=[('potraits', 'Potrait'), ('landscapes', 'Landscape'), ('animals', 'Animals'), ('streets', 'Street'), ('designs', 'Design')], max_length=10),
        ),
    ]
