# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-23 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20160823_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='category',
            field=models.CharField(choices=[('portraits', 'Portrait'), ('landscapes', 'Landscape'), ('streets', 'Street'), ('designs', 'Design')], max_length=10),
        ),
    ]
