# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-24 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_auto_20160825_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='category',
            field=models.CharField(choices=[('portraits', 'Portrait'), ('landscapes', 'Landscape'), ('streets', 'Street'), ('designs', 'Design'), ('still-life', 'Still life')], max_length=10),
        ),
    ]
