# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-22 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0008_auto_20160923_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='size',
            field=models.CharField(choices=[('portraits', 'Portrait'), ('landscapes', 'Landscape')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
